export const LOGIN = "LOGIN";
export const ISLOGGEDIN = "ISLOGGEDIN";
export const REGISTER = "REGISTER";
export const LOGOUT = "LOGOUT";
export const UPDATE_USER = "UPDATE_USER";
export const SET_SOCKET = "SET_SOCKET";
export const PHONENUMBER_ENTERED = "PHONENUMBER_ENTERED";

export const INCREASE_PROGRESS_LEVEL = "INCREASE_PROGRESS_LEVEL";
export const DECREASE_PROGRESS_LEVEL = "DECREASE_PROGRESS_LEVEL";
export const SET_PROGRESS_LEVEL = "REGISTER";

export const PHONE_NUMBER_VALIDATION_START = "PHONE_NUMBER_VALIDATION_START";
export const PHONE_NUMBER_VALIDATION_SUCCESS =
  "PHONE_NUMBER_VALIDATION_SUCCESS";
export const PHONE_NUMBER_VALIDATION_FAIL = "PHONE_NUMBER_VALIDATION_FAIL";

export const OTP_VALIDATION_START = "OTP_VALIDATION_START";
export const OTP_VALIDATION_SUCCESS = "OTP_VALIDATION_SUCCESS";
export const OTP_VALIDATION_FAIL = "OTP_VALIDATION_FAIL";

export const USER_INFO_REGISTER_START = "USER_INFO_REGISTER_START";
export const USER_INFO_REGISTER_SUCCESS = "USER_INFO_REGISTER_SUCCESS";
export const USER_INFO_REGISTER_FAIL = "USER_INFO_REGISTER_FAIL";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CHANGE_PHONE_NUMBER = "AUTH_CHANGE_PHONE_NUMBER";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";